package kr.imcf.ott.domain;

import java.util.Date;

public class TblAccount {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_account.id
     *
     * @mbg.generated Sat Jun 11 20:37:15 KST 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_account.name
     *
     * @mbg.generated Sat Jun 11 20:37:15 KST 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_account.accessToken
     *
     * @mbg.generated Sat Jun 11 20:37:15 KST 2022
     */
    private String accesstoken;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_account.email
     *
     * @mbg.generated Sat Jun 11 20:37:15 KST 2022
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_account.isAuth
     *
     * @mbg.generated Sat Jun 11 20:37:15 KST 2022
     */
    private String isauth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_account.password
     *
     * @mbg.generated Sat Jun 11 20:37:15 KST 2022
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_account.platformType
     *
     * @mbg.generated Sat Jun 11 20:37:15 KST 2022
     */
    private String platformtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_account.profileImage
     *
     * @mbg.generated Sat Jun 11 20:37:15 KST 2022
     */
    private String profileimage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_account.refreshToken
     *
     * @mbg.generated Sat Jun 11 20:37:15 KST 2022
     */
    private String refreshtoken;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_account.createdDate
     *
     * @mbg.generated Sat Jun 11 20:37:15 KST 2022
     */
    private Date createddate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_account.modifiedDate
     *
     * @mbg.generated Sat Jun 11 20:37:15 KST 2022
     */
    private Date modifieddate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_account.id
     *
     * @return the value of tbl_account.id
     *
     * @mbg.generated Sat Jun 11 20:37:15 KST 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_account.id
     *
     * @param id the value for tbl_account.id
     *
     * @mbg.generated Sat Jun 11 20:37:15 KST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_account.name
     *
     * @return the value of tbl_account.name
     *
     * @mbg.generated Sat Jun 11 20:37:15 KST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_account.name
     *
     * @param name the value for tbl_account.name
     *
     * @mbg.generated Sat Jun 11 20:37:15 KST 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_account.accessToken
     *
     * @return the value of tbl_account.accessToken
     *
     * @mbg.generated Sat Jun 11 20:37:15 KST 2022
     */
    public String getAccesstoken() {
        return accesstoken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_account.accessToken
     *
     * @param accesstoken the value for tbl_account.accessToken
     *
     * @mbg.generated Sat Jun 11 20:37:15 KST 2022
     */
    public void setAccesstoken(String accesstoken) {
        this.accesstoken = accesstoken == null ? null : accesstoken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_account.email
     *
     * @return the value of tbl_account.email
     *
     * @mbg.generated Sat Jun 11 20:37:15 KST 2022
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_account.email
     *
     * @param email the value for tbl_account.email
     *
     * @mbg.generated Sat Jun 11 20:37:15 KST 2022
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_account.isAuth
     *
     * @return the value of tbl_account.isAuth
     *
     * @mbg.generated Sat Jun 11 20:37:15 KST 2022
     */
    public String getIsauth() {
        return isauth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_account.isAuth
     *
     * @param isauth the value for tbl_account.isAuth
     *
     * @mbg.generated Sat Jun 11 20:37:15 KST 2022
     */
    public void setIsauth(String isauth) {
        this.isauth = isauth == null ? null : isauth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_account.password
     *
     * @return the value of tbl_account.password
     *
     * @mbg.generated Sat Jun 11 20:37:15 KST 2022
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_account.password
     *
     * @param password the value for tbl_account.password
     *
     * @mbg.generated Sat Jun 11 20:37:15 KST 2022
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_account.platformType
     *
     * @return the value of tbl_account.platformType
     *
     * @mbg.generated Sat Jun 11 20:37:15 KST 2022
     */
    public String getPlatformtype() {
        return platformtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_account.platformType
     *
     * @param platformtype the value for tbl_account.platformType
     *
     * @mbg.generated Sat Jun 11 20:37:15 KST 2022
     */
    public void setPlatformtype(String platformtype) {
        this.platformtype = platformtype == null ? null : platformtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_account.profileImage
     *
     * @return the value of tbl_account.profileImage
     *
     * @mbg.generated Sat Jun 11 20:37:15 KST 2022
     */
    public String getProfileimage() {
        return profileimage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_account.profileImage
     *
     * @param profileimage the value for tbl_account.profileImage
     *
     * @mbg.generated Sat Jun 11 20:37:15 KST 2022
     */
    public void setProfileimage(String profileimage) {
        this.profileimage = profileimage == null ? null : profileimage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_account.refreshToken
     *
     * @return the value of tbl_account.refreshToken
     *
     * @mbg.generated Sat Jun 11 20:37:15 KST 2022
     */
    public String getRefreshtoken() {
        return refreshtoken;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_account.refreshToken
     *
     * @param refreshtoken the value for tbl_account.refreshToken
     *
     * @mbg.generated Sat Jun 11 20:37:15 KST 2022
     */
    public void setRefreshtoken(String refreshtoken) {
        this.refreshtoken = refreshtoken == null ? null : refreshtoken.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_account.createdDate
     *
     * @return the value of tbl_account.createdDate
     *
     * @mbg.generated Sat Jun 11 20:37:15 KST 2022
     */
    public Date getCreateddate() {
        return createddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_account.createdDate
     *
     * @param createddate the value for tbl_account.createdDate
     *
     * @mbg.generated Sat Jun 11 20:37:15 KST 2022
     */
    public void setCreateddate(Date createddate) {
        this.createddate = createddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_account.modifiedDate
     *
     * @return the value of tbl_account.modifiedDate
     *
     * @mbg.generated Sat Jun 11 20:37:15 KST 2022
     */
    public Date getModifieddate() {
        return modifieddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_account.modifiedDate
     *
     * @param modifieddate the value for tbl_account.modifiedDate
     *
     * @mbg.generated Sat Jun 11 20:37:15 KST 2022
     */
    public void setModifieddate(Date modifieddate) {
        this.modifieddate = modifieddate;
    }
}