######################################
## Server Port
#######################################
server:
  port: 8080
#
#  tomcat:
#    basedir: .
#    accesslog:
#      enabled: true
#      suffix: .log
#      prefix: access_log
#      file-date-format: .yyyy-MM-dd
#      pattern: "%{yyyy-MM-dd HH:mm:ss}t %s %r %{User-Agent}i %{Referer}i %a %b %D"

######################################
## Logging Config
#######################################
logging:
  level:
    jdbc.audit: off
    #    jdbc: off
    #    sqlonly: off
    #    sqltiming: off
    jdbc.sqlonly: off
    jdbc.sqltiming: off
    resultsettable: info
    audit: off
    #    resultset: off
    connection: off
    #    sql: info
    #    jdbc: error
    #    resultsettable: info
    #    root: debug
    root: info
    org.springframework.core: info
    org.springframework.web: info
    org.springframework.beans: info
    org.springframework.context: info
    org.springframework.orm: info

    #    org.hibernate.jpa: info
    #    org.hibernate.type.descriptor.sql: info
    #    kr.imcf.ott: debug



######################################
## Spring bean override option
#######################################
spring:
  redis:
    host: ${REDIS_IP}
    port: ${REDIS_PORT}
    connect-timeout: 1000000
  main:
    allow-bean-definition-overriding: true

  #######################################
  ## Spring Mybatis Config
  #######################################
  mybatis:
    config: config/mybatis-config.xml
    mapper: classpath:mybatis/mariadb/*.xml

  #  h2:
  #    console:
  #        enabled: true
  #        path: /h2-console



  ######################################
  ## DEV TOOL
  #######################################
  devtools:
    add-properties: true



  ######################################
  ## OPEN SESSION IN VIEW
  ## (JPA 영속성 컨텍스트 유지 범위)
  ######################################
  jpa:
    open-in-view: true

    ######################################
    ## spring generate ddl
    ## 주의!!!!
    ## 생각 없이 바꾸지 말것
    ## 운영에서 none이 아니면, 테이블 날라감
    ######################################
    hibernate:
      ddl-auto: validate
      dialect: org.hibernate.dialect.MariaDB103Dialect
      show_sql: true
      format_sql: true
      use_sql_comments: true

  ######################################
  ## View JSP
  ######################################
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

  ######################################
  ## Spring Security Test Info
  #######################################
  security:
    user:
      name: imcf
      password: imcf
      roles:
        - ADMIN

  ######################################
  ## Spring output colorful
  #######################################
  output:
    ansi:
      enabled: ALWAYS

  ######################################
  ## Database connection Infomation
  #######################################
  datasource:
    tomcat:
      test-on-borrow: true
      validation-query: SELECT 1

    mariadb:
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url: jdbc:log4jdbc:mariadb://${DB_IP}:${DB_PORT}/${DB_NAME}?${DB_OPT}
      username: ${DB_USERNAME}
      password: ${DB_PASSWORD}