package kr.imcf.ott.persistence.mapper;

import java.util.List;
import kr.imcf.ott.domain.TblAccount;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface TblAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_account
     *
     * @mbg.generated Sat Jun 11 20:37:15 KST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_account
     *
     * @mbg.generated Sat Jun 11 20:37:15 KST 2022
     */
    int insert(TblAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_account
     *
     * @mbg.generated Sat Jun 11 20:37:15 KST 2022
     */
    TblAccount selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_account
     *
     * @mbg.generated Sat Jun 11 20:37:15 KST 2022
     */
    List<TblAccount> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_account
     *
     * @mbg.generated Sat Jun 11 20:37:15 KST 2022
     */
    int updateByPrimaryKey(TblAccount record);
}